<a href="https://colab.research.google.com/github/Silver272/Micro-credential-pg/blob/main/Intro_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy (or Numpy) is a Pyhton Library or Module design for Linear Algebra and Statistical Computation.
It is one of the most important modules in python for Data Science since most all of the libraries necessary for  rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to other programming language libraries such as C++. 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


_______________________________

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We will not have the time to cover them all; we will, however, focus on some of the most important topics such as vectors, arrays, matrices, and number generation. Let's start by discussing arrays.

## Numpy Arrays

NumPy arrays are the main objects that we will use in this class. 

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,110,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((15,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [ ]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((30,30))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(5)

array([0.82452298, 0.53190039, 0.88451572, 0.82487918, 0.46064489])

In [ ]:
np.random.rand(10,10)

array([[0.03051235, 0.06423687, 0.14175373, 0.80489676, 0.33988241,
        0.27789247, 0.57947157, 0.02022229, 0.4908569 , 0.12382858],
       [0.61054994, 0.95222674, 0.26608826, 0.37377291, 0.12104617,
        0.51887943, 0.38363962, 0.8754735 , 0.79138198, 0.53870243],
       [0.94157036, 0.44040192, 0.58718694, 0.2859847 , 0.32790451,
        0.69381132, 0.44396874, 0.3184701 , 0.68366812, 0.90217942],
       [0.35216995, 0.13933605, 0.86562793, 0.97222886, 0.57855783,
        0.74958035, 0.16143831, 0.36915548, 0.03326778, 0.29200673],
       [0.63144293, 0.47864236, 0.16568285, 0.90478438, 0.92845686,
        0.3148213 , 0.47608943, 0.58345725, 0.13915651, 0.05658706],
       [0.7675753 , 0.29121692, 0.80677122, 0.42032026, 0.79324657,
        0.31854672, 0.88909785, 0.53459079, 0.34620512, 0.87914948],
       [0.99837989, 0.46506228, 0.83252419, 0.25473831, 0.14854029,
        0.57689804, 0.70309557, 0.14551491, 0.06578836, 0.00477568],
       [0.78490206, 0.04271595, 0.1202141

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(20)

array([-1.85655659,  0.4047703 , -0.2987308 , -0.38931307, -0.70748111,
        0.30598648,  0.7579694 , -0.32554902, -1.46763497,  0.42467655,
       -0.9132979 , -0.94073301,  1.01234909,  1.07534019,  0.7343724 ,
       -0.64888355,  0.05487716,  0.98998287, -1.55520869,  0.0897543 ])

In [ ]:
np.random.randn(5,5)

array([[-1.28425039e-03,  1.47065827e-02, -1.13268926e+00,
         6.06117707e-01,  9.03926615e-01],
       [-3.99375453e-01,  6.51438555e-01, -7.69114537e-01,
         1.42359687e+00,  6.49208457e-01],
       [-1.06612830e+00,  1.55520510e+00, -1.97039957e+00,
         4.53359949e-01, -1.06154510e+00],
       [ 1.12592613e+00,  8.37620342e-01, -1.39658496e+00,
        -1.27221190e-01, -5.88786571e-01],
       [-5.42738319e-01, -7.41803604e-01,  6.29955941e-01,
         2.71765115e-01,  1.04256695e-01]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,500)

198

In [ ]:
np.random.randint(1,1000,100)

array([281,  70,  66, 252, 138, 993, 494, 993, 280,  33,  84, 576, 146,
       783, 572, 486, 254, 202, 610, 425, 344, 399, 846, 529, 271, 322,
        81, 649, 971, 518, 128,   9, 498, 142, 703,  15, 259, 800, 779,
       662, 459,  76, 304, 842,  93,  28, 119, 253, 835, 348,  92,  61,
       962, 285,   4, 364, 649, 413, 151, 998, 493, 492, 455, 901, 673,
        19, 583, 663, 878, 120, 630, 119,  95, 228,  68, 689, 449, 743,
       771, 395,  22, 200, 104, 926, 492, 181, 909,  26, 172, 170, 929,
       433,  57, 642, 836, 428, 701, 850, 278, 143])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(50)
ranarr = np.random.randint(0,500,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
ranarr

array([318, 287, 230, 322, 366,  14, 256, 247, 298, 419])

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([318, 287, 230, 322, 366,  14, 256, 247, 298, 419])

In [ ]:
ranarr.max()

419

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.min()

14

In [ ]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(50,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr.reshape(2,25).shape

(2, 25)

In [ ]:
arr.reshape(25,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [ ]:
arr.reshape(25,2).shape

(25, 2)

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

## Indexing and Selection

In [ ]:
#Creating sample array
arr = np.arange(0,15)

In [ ]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:


The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,20)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:8]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Indexing a 2D array (matrices)

The general format is `arr_2d[row][col]` or `arr_2d[row,col]`. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1, 0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help

Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## NumPy Operations

### Arithmetic

You can perform array with array (also knows as Matrix operations) arithmetic, or scalar with array arithmetic.

In [ ]:
arr = np.arange(0,100) # array range
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr + arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [ ]:
arr * arr

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
       0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816,
       0.02      , 0.01960784, 0.01923077, 0.01886792, 0.01851852,
       0.01818182, 0.01785714, 0.01754386, 0.01724138, 0.01694915,
       0.01666667, 0.01639344, 0.01612903, 0.01587302, 0.015625  ,
       0.01538462, 0.01515152, 0.01492537, 0.01470588, 0.01449275,
       0.01428571, 0.01408451, 0.01388889, 0.01369863, 0.01351

In [ ]:
arr**3

array([     0,      1,      8,     27,     64,    125,    216,    343,
          512,    729,   1000,   1331,   1728,   2197,   2744,   3375,
         4096,   4913,   5832,   6859,   8000,   9261,  10648,  12167,
        13824,  15625,  17576,  19683,  21952,  24389,  27000,  29791,
        32768,  35937,  39304,  42875,  46656,  50653,  54872,  59319,
        64000,  68921,  74088,  79507,  85184,  91125,  97336, 103823,
       110592, 117649, 125000, 132651, 140608, 148877, 157464, 166375,
       175616, 185193, 195112, 205379, 216000, 226981, 238328, 250047,
       262144, 274625, 287496, 300763, 314432, 328509, 343000, 357911,
       373248, 389017, 405224, 421875, 438976, 456533, 474552, 493039,
       512000, 531441, 551368, 571787, 592704, 614125, 636056, 658503,
       681472, 704969, 729000, 753571, 778688, 804357, 830584, 857375,
       884736, 912673, 941192, 970299])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are just mathematical operations you can use to perform the operation across the array. Some common ones:

In [ ]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
       7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15,
       4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16,
       2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
       1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
       7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
       3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23,
      

In [ ]:
np.max(arr) #same as arr.max()

99

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265,
       -0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
       -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801,
       -0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
        0.82682868, -0.02655115, -0.85551998, -0.89792768, -0.11

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
       3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
       3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ,
       3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
       4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
       4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
       4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
       4.24849524, 4.26267988, 4.27666612, 4.29045944, 4.30406

# Good Times!